"""
NYSE trading calendar.

Before this existed the app decided the market was open with `weekday() < 5`,
so every holiday looked like a normal session: min_dte dropped to 0 and the
finder offered "0DTE" contracts on a closed market. Early closes were worse
than wrong — 0DTE time value is computed as minutes until 16:00, so on a 13:00
close the model thought there were three extra hours of life in the contract.

Holiday dates below are independently known NYSE observances, not outputs of
the implementation.
"""
from datetime import date, datetime, time
import zoneinfo

import pytest

from core.market_calendar import (
    is_trading_day, is_market_open, market_close_time, next_trading_day,
)

ET = zoneinfo.ZoneInfo("America/New_York")

HOLIDAYS_2026 = [
    (date(2026, 1, 1),  "New Year's Day"),
    (date(2026, 1, 19), "MLK Day"),
    (date(2026, 2, 16), "Washington's Birthday"),
    (date(2026, 4, 3),  "Good Friday"),
    (date(2026, 5, 25), "Memorial Day"),
    (date(2026, 6, 19), "Juneteenth"),
    (date(2026, 7, 3),  "Independence Day observed (Jul 4 = Sat)"),
    (date(2026, 9, 7),  "Labor Day"),
    (date(2026, 11, 26), "Thanksgiving"),
    (date(2026, 12, 25), "Christmas"),
]

HOLIDAYS_2027 = [
    (date(2027, 1, 1),  "New Year's Day"),
    (date(2027, 1, 18), "MLK Day"),
    (date(2027, 2, 15), "Washington's Birthday"),
    (date(2027, 3, 26), "Good Friday"),
    (date(2027, 5, 31), "Memorial Day"),
    (date(2027, 6, 18), "Juneteenth observed (Jun 19 = Sat)"),
    (date(2027, 7, 5),  "Independence Day observed (Jul 4 = Sun)"),
    (date(2027, 9, 6),  "Labor Day"),
    (date(2027, 11, 25), "Thanksgiving"),
    (date(2027, 12, 24), "Christmas observed (Dec 25 = Sat)"),
]


@pytest.mark.parametrize("day,label", HOLIDAYS_2026 + HOLIDAYS_2027)
def test_known_holidays_are_not_trading_days(day, label):
    assert is_trading_day(day) is False, f"{day} ({label}) treated as a session"


def test_ordinary_weekdays_are_trading_days():
    for d in [date(2026, 8, 17), date(2026, 3, 10), date(2026, 10, 1)]:
        assert is_trading_day(d) is True


def test_weekends_are_not_trading_days():
    assert is_trading_day(date(2026, 8, 15)) is False  # Saturday
    assert is_trading_day(date(2026, 8, 16)) is False  # Sunday


def test_early_closes_end_at_1pm():
    # Day after Thanksgiving and Christmas Eve close at 13:00 ET.
    assert market_close_time(date(2026, 11, 27)) == time(13, 0)
    assert market_close_time(date(2026, 12, 24)) == time(13, 0)


def test_normal_session_ends_at_4pm():
    assert market_close_time(date(2026, 8, 17)) == time(16, 0)


def test_market_open_respects_holidays():
    # 11:00 ET on Thanksgiving — mid-session by the clock, but closed.
    thanksgiving = datetime(2026, 11, 26, 11, 0, tzinfo=ET)
    assert is_market_open(thanksgiving) is False


def test_market_open_respects_early_close():
    after_early_close = datetime(2026, 11, 27, 14, 0, tzinfo=ET)
    assert is_market_open(after_early_close) is False
    during = datetime(2026, 11, 27, 11, 0, tzinfo=ET)
    assert is_market_open(during) is True


def test_market_open_normal_session_bounds():
    assert is_market_open(datetime(2026, 8, 17, 9, 29, tzinfo=ET)) is False
    assert is_market_open(datetime(2026, 8, 17, 9, 30, tzinfo=ET)) is True
    assert is_market_open(datetime(2026, 8, 17, 15, 59, tzinfo=ET)) is True
    assert is_market_open(datetime(2026, 8, 17, 16, 1, tzinfo=ET)) is False


def test_next_trading_day_skips_holiday_weekend():
    # Thu 2026-11-26 is Thanksgiving; next session is Fri the 27th (early close).
    assert next_trading_day(date(2026, 11, 25)) == date(2026, 11, 27)
    # Fri 2026-12-25 Christmas -> Mon 2026-12-28.
    assert next_trading_day(date(2026, 12, 24)) == date(2026, 12, 28)


def test_new_year_observed_in_prior_year_is_caught():
    # Jan 1 2028 is a Saturday, so the NYSE observes it on Fri 2027-12-31.
    # Looking only at holidays(day.year) misses it, since the observance is
    # generated by the *following* year's rules.
    assert is_trading_day(date(2027, 12, 31)) is False
    assert next_trading_day(date(2027, 12, 30)) == date(2028, 1, 3)


def test_new_year_observed_in_following_year():
    # Jan 1 2028 (Sat) rolls back; Jan 1 2033 is a Saturday too. Spot-check the
    # forward rule as well: Jan 1 2034 is a Sunday -> observed Mon Jan 2.
    assert is_trading_day(date(2034, 1, 2)) is False


# ─── 0DTE time-value must use the real close ──────────────────────────────────
def test_minutes_to_close_honours_early_close():
    from core.market_calendar import minutes_to_close
    # 12:00 ET on the day after Thanksgiving: 60 minutes left, not 240.
    assert minutes_to_close(datetime(2026, 11, 27, 12, 0, tzinfo=ET)) == pytest.approx(60.0)
    # Same clock time on a normal session: 240 minutes.
    assert minutes_to_close(datetime(2026, 8, 17, 12, 0, tzinfo=ET)) == pytest.approx(240.0)


def test_minutes_to_close_zero_when_shut():
    from core.market_calendar import minutes_to_close
    assert minutes_to_close(datetime(2026, 11, 26, 12, 0, tzinfo=ET)) == 0.0   # Thanksgiving
    assert minutes_to_close(datetime(2026, 8, 16, 12, 0, tzinfo=ET)) == 0.0    # Sunday


def test_get_best_contract_0dte_branch_has_no_undefined_names():
    # Regression: the 0DTE branch referenced _now_et after the market-hours block
    # that defined it was replaced. Only reachable when a 0DTE expiry exists, so
    # no weekend test would ever catch it — it would raise NameError mid-session.
    import ast
    import core.options as scanner   # get_best_contract's module
    tree = ast.parse(open(scanner.__file__).read())
    fn = next(n for n in ast.walk(tree)
              if isinstance(n, ast.FunctionDef) and n.name == "get_best_contract")
    stored = {n.id for n in ast.walk(fn)
              if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Store)}
    loaded = {n.id for n in ast.walk(fn)
              if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)}
    # Names the function reads must be assigned locally, be module-level, or be
    # builtins. Anything else is a NameError waiting for the right market state.
    import builtins
    known = stored | set(dir(scanner)) | set(dir(builtins)) | {a.arg for a in fn.args.args}
    known |= {d.name for d in ast.walk(fn) if isinstance(d, ast.FunctionDef)}
    for node in ast.walk(fn):          # lambda params and comprehension targets
        if isinstance(node, ast.Lambda):
            known |= {a.arg for a in node.args.args}
        if isinstance(node, ast.comprehension):
            known |= {n.id for n in ast.walk(node.target) if isinstance(n, ast.Name)}
    assert not (loaded - known), f"undefined in get_best_contract: {sorted(loaded - known)}"
